site_name: WLED
site_author: Christian Schwinne (Aircoookie)
#site_url: https://wled.app
repo_name: WLED
repo_url: https://github.com/Aircoookie/WLED
repo_title: WLED Repository
#copyright: Copyright &copy; 2016-2021 Christian Schwinne, Contributors
edit_uri: https://github.com/Aircoookie/WLED-Docs/edit/master/docs
theme:
  name: material
  custom_dir: docs/assets/overrides
  language: en
  logo: assets/images/ui/akemi/000_base.png
  icon: 
    repo: fontawesome/brands/github
  # features: 
  #   - navigation.tabs
  palette:
    - scheme: slate
      primary: red
      accent: blue
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Light Mode
    - scheme: default
      primary: deep orange
      accent: blue
      toggle: 
        icon: material/toggle-switch
        name: Light Mode
plugins: 
  - search
markdown_extensions:
  - admonition
  - attr_list
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/KuqP7NE
      name: Discord
    - icon: fontawesome/brands/discourse
      link: https://wled.discourse.group/
      name: Forum
    - icon: fontawesome/solid/code
      link: https://gitpod.io/#https://github.com/Aircoookie/WLED
      name: Gitpod
extra_css:
  - assets/stylesheets/global.css
  